compile:
	g++  ./source/*.cpp -I ../include/  -o encryptor.exe
s: # static compile
	g++  ./source/*.cpp -I ../include/ -static -o DiyEncryptor_v2.exe
s32: # static 32bits
	g++  ./source/*.cpp -I ../include/ -static -m32 -o DiyEncryptor_m32_v2.exe
